### ISSUE TITLE
[Question] Reading arrays in compound dataset?

### ISSUE THREAD

**Issue by nprezant** [Apollo3zehn/PureHDF#10]
Hi! I'm wondering if there are any examples or support for reading arrays in a compound dataset?

Something like this:

```cs
internal struct QUAD_CN
{
    public int ID;
    public string TERM; // length: 8
    public int[] GRID; // length: 5
    public float[] FD1; // length: 5
}
```

**Comment by Apollo3zehn** [comment]
This is a message I post to all recent issues: I have just renamed the project from HDF5.NET to PureHDF for my preparations of a soon to come beta release. Please note that the Nuget package name has also changed and can be found here now: https://www.nuget.org/packages/PureHDF.
