### ISSUE TITLE
Accessing Enumeration nested within Compound Type 

### ISSUE THREAD

**Issue by rtran89** [Apollo3zehn/PureHDF#119]
Hi @Apollo3zehn
Thanks for all your work.
I just have a question whether there are any other way to accessing Enumeration that are stored in CompountType.
I can see currently it simply returns the type with no information under it as seen below:
https://github.com/Apollo3zehn/PureHDF/blob/a26c5314a953344a97871235c6982523133975aa/src/PureHDF/API.Reading/IH5DataType.cs#L83

When I debug I can see that there are further data stored within a private member _dataType.
![image](https://github.com/Apollo3zehn/PureHDF/assets/140033495/96cf2f34-8813-4da1-8654-74fb8a2e70c5)

**Comment by Apollo3zehn** [comment]
I`ll release a new version with the type information exposed in ~1 hour

**Comment by Apollo3zehn** [comment]
[v2.0.1](https://www.nuget.org/packages/PureHDF/2.0.1) is being released now. It may take a few minutes until you can access it on Nuget (it needs to be indexed first).

I hope this solves your problem :-)
