### ISSUE TITLE
Integer overflow in `SelectionHelper.DecodeStream`

### ISSUE THREAD

**Issue by audunska** [Apollo3zehn/PureHDF#124]
I am reading bathymetric data from GEBCO - the link "Download GEBCO_2022 Grid" from this page:
https://www.gebco.net/data_and_products/historical_data_sets/#gebco_2022

The following code works:
```c#
var path = @"path\to\GEBCO_2022.nc";
using var file = H5File.OpenRead(path);
file.Dataset("/elevation").Read<short>(fileSelection: new PointSelection(new ulong[1, 2] { { 12000, 12000 } }));
```
however, increasing the indices to `{14000, 14000}` fails with an exception saying that we seeked to a negative file position.

The netcdf file is an hdf file with contiguous layout. I followed the reading code path, and found [this line](https://github.com/Apollo3zehn/PureHDF/blob/ddb83dc9956697829dd5f92ab2dcad19e02ed7e5/src/PureHDF/Selections/SelectionHelper.cs#L344):
```c#
sourceStream.Seek(currentOffset * decodeInfo.SourceTypeSize, SeekOrigin.Begin);
```

Here, `currentOffset` and `decodeInfo.SourceTypeSize` are of type `int` - the offset is cast to `int` a few lines above. Thus the multiplication (in this case by 2) happens in the `int` data type. The offset has been computed as 1036812000. The double of that is a negative `int`, so the subsequent cast to `long` results in a negative number.

I'd have a go at a fix, but I am not sure about the full context here: Why was the offset cast to `int` in the first place?

**Comment by audunska** [comment]
In fact, increasing the indices to `{28000, 28000}` causes the original `sourceStep.Offset` to be bigger than 2^31, so the [cast to `int` ](https://github.com/Apollo3zehn/PureHDF/blob/ddb83dc9956697829dd5f92ab2dcad19e02ed7e5/src/PureHDF/Selections/SelectionHelper.cs#L319) is already invalid.

Of course, you'd expect numbers this large from a 7.5GB file with a contiguous layout. The offset I see is just the flattened index `86400 * 28000 + 28000`, where 86400 is the length of the longitude dimension.

**Comment by Apollo3zehn** [comment]
It has been fixed on `dev` and the newly created `v1` branch. Do you need a bug-fix release on Nuget? I could do it tomorrow, otherwise it will be part of a regular release in a while.

**Comment by Apollo3zehn** [comment]
I am not sure why I had this cast. Maybe because this class looked a bit different a while ago where I not only used `Stream` but also `Memory<T>` to read and write data and `Memory<T>.Slice()`  expects `int` parameters. But that is just a guess.

**Comment by audunska** [comment]
Ah, I forgot to look in the dev branch.

No need to rush with the release.

**Comment by Apollo3zehn** [comment]
Since there are now two bugs being solved and it could potentially take long time for more changes on the v1 branch I just started the release process. v1.0.1 should be release in the next couple of minutes.
