### ISSUE TITLE
Large write returns without error, but not all data is written

### ISSUE THREAD

**Issue by marklam** [Apollo3zehn/PureHDF#131]
I've created a repro case
https://github.com/marklam/Roundtrip3DArrayOfStructList/blob/partial-writes/ConsolePureHDFroundtrip/Program.fs

This test case (the branch named partial-writes) creates a 2D array of variable-length lists of structures. It writes 8000 but all entries after 596 are null on readback.

**Comment by Apollo3zehn** [comment]
Version 2.1.1 contains a fix for your issue. The data were written to the wrong position in the file so it appeared as `null` in your sample program. It was a bit difficult to figure out the root cause but I think I found a suitable solution.

**Comment by marklam** [comment]
Looks good to me!
Thanks!
