### ISSUE TITLE
how to traverse the attributes of a group or a dataset?

### ISSUE THREAD

**Issue by Fokatu** [Apollo3zehn/PureHDF#15]
traverse the attributes  and show the corresponding contents.
Thanks

**Comment by Apollo3zehn** [comment]
This is a message I post to all recent issues: I have just renamed the project from HDF5.NET to PureHDF for my preparations of a soon to come beta release. Please note that the Nuget package name has also changed and can be found here now: https://www.nuget.org/packages/PureHDF.
