### ISSUE TITLE
Field "_dataType" present in the type "HDF5.NET.H5DataType" can be exposed?

### ISSUE THREAD

**Issue by dularish** [Apollo3zehn/PureHDF#20]
Hello,

I have been trying to use HDF5.NET library for reading HDF5 files. I would say that HDF5.NET library is very .NET developer friendly.

We use compound types in our applications, and one application would generate HDF5 files, and other application would need to read the HDF5 files, As far as I could read the documentation, HDF5.NET library requires explicit types that would describe the schema for compound types. But in our case, it is not possible to have a common API for all our applications just to make schema types in sync.

In HDF.PInvoke library, there is a possibility to get member names, datatypes and read the binary data for a compound type data, and let the application handle the reading of compound type, which works for our scenario.

If there is similar option in "HDF5.NET" library, it would be helpful for us. The only thing that is stopping from doing it is that the field "_dataType" present in the type "HDF5.NET.H5DataType" is not exposed. Is it possible to expose the field "_dataType"?

**Comment by Apollo3zehn** [comment]
This is a message I post to all recent issues: I have just renamed the project from HDF5.NET to PureHDF for my preparations of a soon to come beta release. Please note that the Nuget package name has also changed and can be found here now: https://www.nuget.org/packages/PureHDF.
