### ISSUE TITLE
Index out of range when trying to read dataset of VariableLength

### ISSUE THREAD

**Issue by neroarth94** [Apollo3zehn/PureHDF#28]
Hi, I am trying to read a HDF5 file and came across an issue when trying to read a dataset that is VariableLength type.
To read the dataset, i just use the code:
`var data = dataset.ReadString();`

but it fails with the following exception:
```
 System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. 
 (Parameter 'index')
    at PureHDF.H5ReadUtils.ReadString(H5Context context, DatatypeMessage datatype, Span`1 data, String[] result) in 
 /home/runner/work/PureHDF/PureHDF/src/PureHDF/Utils/H5ReadUtils.cs:line 293
    at PureHDF.H5Dataset.ReadString(Selection fileSelection, Selection memorySelection, UInt64[] memoryDims, 
 H5DatasetAccess datasetAccess) in /home/runner/work/PureHDF/PureHDF/src/PureHDF/API/H5Dataset.cs:line 270
```

It works fine if I read dataset with String type.
May I know what else I need to specify to be able to read the VariableLength?
The attached screenshot is an example of the dataset properties
![image](https://user-images.githubusercontent.com/59238910/217763508-c0918dba-f585-4220-8755-4ed6fd4a0d0d.png)

Thank you.

**Comment by Apollo3zehn** [comment]
HI, could you please provide a small sample file? This looks like a bug. Thank you!

**Comment by neroarth94** [comment]
Hi @Apollo3zehn , the sample file as below. Git doesn't let me upload hdf5 extension so i need to zip it
[example.zip](https://github.com/Apollo3zehn/PureHDF/files/10702770/example.zip)

**Comment by Apollo3zehn** [comment]
Thank you. I found the issue. How has this file been created? Did you delete any objects after file creation? I think the problem is easy to solve on my side but I would first like to understand how such an internal file structure is produced :-)

**Comment by neroarth94** [comment]
Steps to reproduce:

1. Open HDFView
2. Create a new hdf5 file
3. Create new dataset with variable length as show in attached screenshot
4. it would catch the exception when reading variable length

I did not delete any objects or have any further steps other than the above
Sorry but may I know when will you roll out the fix because I would like to proceed with my work. 
thank you~

![image](https://user-images.githubusercontent.com/59238910/218036587-1764ffe7-e6b9-43d1-aaa3-4916e5ccd501.png)

**Comment by Apollo3zehn** [comment]
It is fixed now (I hope :-)). I only have access to my mobile phone right now and tried to fix it using GitHub Code Spaces. My limited test showed that the exception does not occur anymore. Release v1.0.0-alpha.24 contains the fix.
