### ISSUE TITLE
Unable to read variable-length attribute

### ISSUE THREAD

**Issue by melmar99** [Apollo3zehn/PureHDF#51]
Hello,
reading the variable-length attribute is causing the following exception:  _Exception: Variable-length sequence data can only be decoded as array (incompatible type: System.String)._
The exception says that type _System.String_ is incompatible even though a type _string[]_ has been used.
The code below successfully reads the variable-length type dataset, but reading the variable-length type attribute fails.

```
            var dataset_NUTS_keys = nativeFile.Dataset("/NUTS_keys");

            foreach (var attribute in dataset_NUTS_keys.Attributes())
            {
                var typeClass = attribute.Type.Class; // attribute.Type.Class is VariableLength

                //This attribute has the name DIMENSION_LIST and should contain the text 'NUTS'
                string[] attributeArray = attribute.Read<string[]>(); // Exception
            }

            var typeClass_NUTS_keys = dataset_NUTS_keys.Type.Class; // Type.Class is VariableLength

            string[] NUTS_keys = dataset_NUTS_keys.Read<string[]>(); // Successful
```

A copy of the HDF5 file used is [here](https://drive.google.com/file/d/10diullQzoWEw9R9-FI65Dz0FzCdkXDvb/view) 

If _attribute.Read<string[][]>()_ is used the exception is: _Bitfield data can only be decoded as NativeObjectReference1 (incompatible type: System.String)_
If _NativeObjectReference1_ is used the exception is: _Unable to decode a reference type as value type._

Any help would be greatly appreciated.

**Comment by veltrupdev** [comment]
Thanks for reporting the issue, I will check it now

**Comment by Apollo3zehn** [comment]
Thanks for reporting that issue, I will check it now!

**Comment by melmar99** [comment]
Yes it works. Thank you very much for your help.

**Comment by Apollo3zehn** [comment]
Perfect :-)
