### ISSUE TITLE
Support for .Net 8.0?

### ISSUE THREAD

**Issue by neroarth94** [Apollo3zehn/PureHDF#59]
.Net 8.0 has been released for some time already. Just wondering is there any plan to upgrade the framework to .net8? since it is a LTS

**Comment by Apollo3zehn** [comment]
I already tried to upgrade but something is handled different in the .NET 8 SDK dependency management such that it cannot compile anymore. I need to investigate this and will upgrade then.

**Comment by neroarth94** [comment]
ok got it. thanks for the response. hopefully can be upgraded soon

**Comment by Apollo3zehn** [comment]
Its done
