### ISSUE TITLE
Read old style groups as UTF-8 - What does the spec say?

### ISSUE THREAD

**Issue by Apollo3zehn** [Apollo3zehn/PureHDF#61]
https://github.com/jamesmudd/jhdf/issues/539#issuecomment-1923308452
https://github.com/jamesmudd/jhdf/pull/544/commits/14e939d697b2a90c8bdf392089859e29e3579654

**Comment by jamesmudd** [comment]
Yes I thought about this as well. I couldn't see anything definitive in the spec, this is an example file were clearly the names are UTF8 encoded (but I don't know how its been created). Pragmatically I decided to change to UTF8 as its compatible with ASCII I don't see any downside, actually made me consider just switching to UTF8 everywhere even where the encoding is specifically defined in the spec and the file. Would be interested what you think on this?

**Comment by Apollo3zehn** [comment]
And none of my tests fail with the change.

**Comment by Apollo3zehn** [comment]
> ... actually made me consider just switching to UTF8 everywhere even where the encoding is specifically defined in the spec and the file. Would be interested what you think on this?

I also thought about this but did not dare yet to do this. This would need some investigation first to detect possible problems. One might be, that writing such files could lead to incompatibilities with the C-library. However, just reading UTF-8 everywhere should be fine I would say.
