### ISSUE TITLE
Honor H5Name for Compound Writing

### ISSUE THREAD

**Issue by Blackclaws** [Apollo3zehn/PureHDF#85]
When writing compound datatypes H5Name is used during read but not for writing.

Not urgent in any case but I saw tried this and it didn't work.

**Comment by Apollo3zehn** [comment]
You need a field/property name mapper for both, reading and writing to take the attribute into account. PureHDF itself has no logic to make use of that attribute. Here is an example from the tests of how to create and use such a mapper:

https://github.com/Apollo3zehn/PureHDF/blob/f7d1521d32e8faa943993befa9eac66572761ce3/tests/PureHDF.Tests/Writing/DatasetTests%40datatypes.cs#L27-L43

If reading is working without this mapper, I am a bit confused :-)

**Comment by Apollo3zehn** [comment]
Maybe I need to update the docs.
