### ISSUE TITLE
How do I write data to an existing native HDF5 file?

### ISSUE THREAD

**Issue by xingLong-xl** [Apollo3zehn/PureHDF#87]
I want to write data to the local HDF5 file, your library does not seem to provide this method, or I did not find it. So far I've seen write methods that overwrite my native files. Does your library support such writing methods? Thank you!

**Comment by Apollo3zehn** [comment]
Hi, thanks for trying out PureHDF. Modifying existing files is out of scope oft this library unfortunately, because that would complicate things very much due to the complexity of the HDF5 specification.
