### ISSUE TITLE
H5Group.Read<T>() fails with "Filter pipeline failed" in 1.0.0-alpha.21

### ISSUE THREAD

**Issue by ccopsey** [Apollo3zehn/PureHDF#9]

**Comment by Apollo3zehn** [comment]
This is a message I post to all recent issues: I have just renamed the project from HDF5.NET to PureHDF for my preparations of a soon to come beta release. Please note that the Nuget package name has also changed and can be found here now: https://www.nuget.org/packages/PureHDF.
